/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    NavAvatar: typeof import('./src/components/nav-sidebar/src/nav-avatar.vue')['default']
    NavSidebar: typeof import('./src/components/nav-sidebar/src/nav-sidebar.vue')['default']
  }
}
