/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    NavAvatar: typeof import('./components/nav-sidebar/src/nav-avatar.vue')['default']
    NavSidebar: typeof import('./components/nav-sidebar/src/nav-sidebar.vue')['default']
  }
}
